### PR TITLE
Update UG output for add

### LINKED ISSUE #168: [PE-D][Tester E] Output result after executing "add" command
May be a little confusing especially for new users when the "Tags: ; Graded Test:" are just left empty. Could consider using "N/A" instead. 

In addition, format of the output shown in the actual app does not match with the one given in the UG (absence of ";" at the end).

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: zannloo/ped#2

### LINKED ISSUE #198: [PE-D][Tester E] "editgrade" command in UG is inconsistent with app
For the "editgrade" command, I tried only editing certain fields such as grades for ra1 or ra2 only and it worked but it does not reflect in the UG that these fields are optional. Could consider adding that it through "[]" as mentioned in the beginning of the UG. 

The command at the header ("editgradedtest") does not match the one that is given in the command format ("editgrade")

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: zannloo/ped#6

### LINKED ISSUE #227: UG Command Summary missing a few commands or typo
image

To Do:
- [x] Change `view` to `viewtasks`
- [x] Remove `addgrade`
- [x] Remove `addcomment`
- [x] Remove `viewcomment`
- [x] Add `list`
- [x] Add `addtask`
- [x] Add `createsession`
- [x] Add `updatesessionremark`
- [x] Add `deletesession`
- [x] Add `addtoconsult`
- [x] Add `removefromconsult`
- [x] Add `deleteconsult`

### LINKED ISSUE #228: Add break lines to UG

### PR DESCRIPTION
**Pull request by raydenlim**

### CODE REVIEW

**Comment by raydenlim** [comment]
RA1, RA2, MIDTERMS, FINALS, PE are all supposed to be optional fields in editgradedtest. However, at least 1 field MUST be present after the `INDEX`, else, throw message error.

✅ editgradedtest INDEX [ra1/SCORE]
✅ editgradedtest INDEX [ra1/SCORE] [ra2/SCORE] [mt/SCORE] [f/SCORE] [pe/SCORE]
❌ editgradedtest INDEX ____  <- blank 


Updated both UG and Message to reinforce this idea across to users

**Comment by raydenlim** [comment]
SLAPP for `EditGradedTestCommandParser`

**Comment by raydenlim** [comment]
Added break lines to UG to make it neater

**Review by Respirayson — APPROVED** [review]
LGTM

**Pull request merged**
